table fPrices
	lineageTag: a98e5d81-1b3f-4da6-8fd5-ed18238bfa74

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 572c47d3-1f93-4210-8076-3c76d04fe1f5
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Close
		dataType: decimal
		lineageTag: 74dfc5b7-63f7-4a15-976d-7f364736c9dd
		summarizeBy: none
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: 14ebdf75-b4f2-43a5-a94e-1a0c3bcb1d73
		summarizeBy: none
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	column Daily_Return
		dataType: decimal
		formatString: 0.0000000000%;-0.0000000000%;0.0000000000%
		lineageTag: 8960afa5-261a-4681-9bca-dc22c133c585
		summarizeBy: none
		sourceColumn: Daily_Return

		annotation SummarizationSetBy = Automatic

	column Daily_return_bin
		dataType: decimal
		formatString: 0%;-0%;0%
		lineageTag: c45bb748-102e-4075-b786-455f90d953e6
		summarizeBy: none
		sourceColumn: Daily_return_bin

		annotation SummarizationSetBy = Automatic

	column 'Running Max Price'
		dataType: decimal
		lineageTag: 1b1a7161-2a03-4d50-a7c3-7dbc1064a9ee
		summarizeBy: none
		sourceColumn: Running Max Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fPrices = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(Web.Contents(sourceUrl),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos", {{"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Daily_Return", type number}, {"Price_Range", type number}, {"Price_Change", type number}}, "en-US"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade",{{"Volume", Int64.Type}, {"Date", type date}}),
				    #"Divided Column" = Table.TransformColumns(#"Tipo Alterado", {{"Daily_Return", each _ / 100, type number}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Divided Column",{{"Daily_Return", Percentage.Type}}),
				    #"Inserted Rounding" = Table.AddColumn(#"Changed Type", "Daily_return_bin", each Number.IntegerDivide([Daily_Return], 0.05) * 0.05, Percentage.Type),
				    Sorted = Table.Buffer(Table.Sort(#"Inserted Rounding", {{"Date", Order.Ascending}})),
				    Indexed = Table.AddIndexColumn(Sorted, "Index", 0, 1, Int64.Type),
				    CloseList = Indexed[Close],
				    AddRunningMax =
				        Table.AddColumn(
				            Indexed,
				            "Running Max Price",
				            each List.Max(List.FirstN(CloseList, [Index] + 1)),
				            type number
				        ),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(AddRunningMax,{"Daily_Return","Date","Volume","Close","Daily_return_bin","Running Max Price"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

