table Grammy_Big_Four_Awards
	lineageTag: bc68528d-426b-4bcc-88e7-f96f9a5598be

	column Year
		dataType: string
		lineageTag: e7a77c0c-b807-463e-a6f0-0e767ec3f61b
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Ceremony_Number
		dataType: string
		lineageTag: f420245e-3e88-4b5a-94ae-baebf190be10
		summarizeBy: none
		sourceColumn: Ceremony_Number

		annotation SummarizationSetBy = Automatic

	column Decade
		dataType: string
		lineageTag: 4b833f9e-13d1-4440-817d-cec2a3b12dae
		summarizeBy: none
		sourceColumn: Decade

		annotation SummarizationSetBy = Automatic

	column Era
		dataType: string
		lineageTag: 94393a55-3c7f-4cd2-a698-3542d0623d22
		summarizeBy: none
		sourceColumn: Era

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 297cf21b-bdb1-4022-8579-0d2d67aaa6eb
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Award_Group
		dataType: string
		lineageTag: d112dae3-f59b-474a-ba07-8c014715b6ed
		summarizeBy: none
		sourceColumn: Award_Group

		annotation SummarizationSetBy = Automatic

	column Winner
		dataType: string
		lineageTag: a9263de2-e6fa-48b8-b29b-ebf5bcb6cc48
		summarizeBy: none
		sourceColumn: Winner

		annotation SummarizationSetBy = Automatic

	column Artist
		dataType: string
		lineageTag: fb66f3f6-c6c5-48f3-81ce-44d8335ee797
		summarizeBy: none
		sourceColumn: Artist

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 41a95f3e-ed31-44bb-994c-6adc57be7822
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Total_Wins
		dataType: string
		lineageTag: 20fa43e2-488b-40ac-885c-b359ff041097
		summarizeBy: none
		sourceColumn: Total_Wins

		annotation SummarizationSetBy = Automatic

	column Category_Total_Winners
		dataType: string
		lineageTag: 66417152-01b7-4ec2-b4c7-b9b10d00a5dc
		summarizeBy: none
		sourceColumn: Category_Total_Winners

		annotation SummarizationSetBy = Automatic

	column Data_Source
		dataType: string
		lineageTag: a2754e08-a822-4fbe-8be1-543f1b8af1bb
		summarizeBy: none
		sourceColumn: Data_Source

		annotation SummarizationSetBy = Automatic

	column Collection_Date
		dataType: string
		lineageTag: b48ca164-b568-42c9-93ba-765a85ca7ff5
		summarizeBy: none
		sourceColumn: Collection_Date

		annotation SummarizationSetBy = Automatic

	partition Grammy_Big_Four_Awards = m
		mode: import
		source =
				let
				    fileName = "Grammy_Big_Four_Awards_20260208_055452.csv",
				    Source = Csv.Document(Web.Contents(sourceDatasetUrl & fileName),[Delimiter=",", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

