table _Measures
	lineageTag: fbd129f1-40a3-44f0-b875-a72cfcfbf149

	measure 'Latest Close Price' =
			
			CALCULATE(
			    MAX(fPrices[Close]),
			    LASTDATE(dCalendar[Date])
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 56ce70a6-1222-44c6-b0d0-1f1c4bf1a667

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Daily Return %' =
			
			VAR PreviousClose =
			    CALCULATE(
			        MAX(fPrices[Close]),
			        DATEADD(dCalendar[Date], -1, DAY)
			    )
			
			RETURN
			
			DIVIDE(
			    MAX(fPrices[Close]) - PreviousClose,
			    PreviousClose
			)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 4e43598e-aea3-46d1-825e-00ce6fe6c17d

	measure 'Cumulative Return %' =
			
			VAR FirstPrice =
			    CALCULATE(
			        FIRSTNONBLANK(fPrices[Close], 1),
			        ALL(dCalendar)
			    )
			
			RETURN
			
			DIVIDE(
			    MAX(fPrices[Close]) - FirstPrice,
			    FirstPrice
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		lineageTag: ae7e1775-e13c-4756-b8aa-0bbc8f4aa8b8

	measure 'Rolling 30d Volatility' =
			
			STDEVX.P(
			    DATESINPERIOD(
			        dCalendar[Date],
			        MAX(dCalendar[Date]),
			        -30,
			        DAY
			    ),
			    [Daily Return %]
			)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 8b3802bb-fe9a-4c7a-8d81-9aeca5cbc332

	measure 'Running Max Price' =
			
			CALCULATE(
			    MAX(fPrices[Close]),
			    FILTER(
			        ALL(dCalendar),
			        dCalendar[Date] <= MAX(dCalendar[Date])
			    )
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0ad7ba6c-0950-41fd-b691-e15f4afebcdf

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Drawdown %' =
			
			DIVIDE(
			    MAX(fPrices[Close]) - [Running Max Price],
			    [Running Max Price]
			)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 5e4e5ea8-4ecc-4e01-8739-cbae807f92ac

	measure 'YTD Return %' =
			
			VAR StartOfYearPrice =
			    CALCULATE(
			        MAX(fPrices[Close]),
			        DATESYTD(dCalendar[Date])
			    )
			
			VAR FirstPriceYTD =
			    CALCULATE(
			        FIRSTNONBLANK(fPrices[Close], 1),
			        DATESYTD(dCalendar[Date])
			    )
			
			RETURN
			
			DIVIDE(
			    [Latest Close Price] - FirstPriceYTD,
			    FirstPriceYTD
			)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 2f2479d6-eb62-4b69-a4ff-1c37939c8343

	measure 'Current Drawdown %' =
			
			CALCULATE(
			    [Drawdown %],
			    LASTDATE(dCalendar[Date])
			)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 7ae8741a-9693-414b-b977-efe5f25ff01a

	measure 'Close Price' = SUM(fPrices[Close])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e615fd18-aa3c-40d6-8db6-06d0f263d30e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Volume = SUM(fPrices[Volume])
		formatString: #,0
		lineageTag: 3ebf9713-c8f7-4591-8c1f-20a047672287

	measure 'Rolling 30d Avg Volume' =
			
			AVERAGEX(
			    DATESINPERIOD(
			        dCalendar[Date],
			        MAX(dCalendar[Date]),
			        -30,
			        DAY
			    ),
			    CALCULATE(SUM(fPrices[Volume]))
			)
		formatString: #,0
		lineageTag: 1d42bdfe-be28-40d1-b1ba-dfe1abac13ab

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Teste = "Teste"
		lineageTag: 80de55b8-cc4e-4eb8-84f2-e6cb285b25e6

	measure 'Previous Latest Close Price' =
			
			CALCULATE(
			    [Latest Close Price],
			    DATEADD(dCalendar[Date], -1, DAY)
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d0787bc4-845c-4c66-b29f-aced359940e5

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Cumulative % detail text' = "Since " & YEAR(MIN(dCalendar[Date]))
		lineageTag: 77293e81-267e-4525-a01f-2a5804bde4db

	measure 'Rolling 30d volatility detail text' = ```
			
			VAR _VOL = [Rolling 30d Volatility]
			
			VAR _LVL = 
			    SWITCH(
			        TRUE,
			        _VOL > 0.4, "High",
			        _VOL > 0.2, "Medium",
			        "Low"
			    )
			
			RETURN
			
			_LVL & " Variance"
			```
		lineageTag: 21e2a612-7ce2-40a0-a2d4-e92d5004fec9

	measure 'All time high price' = MAX(fPrices[Close])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5bd4b5b2-8d9a-448a-9a00-8fff96247ec4

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

