table _Measures
	lineageTag: fbd129f1-40a3-44f0-b875-a72cfcfbf149

	measure 'Latest Close Price' =
			
			CALCULATE(
			    MAX(fPrices[Close]),
			    LASTDATE(dCalendar[Date])
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 56ce70a6-1222-44c6-b0d0-1f1c4bf1a667

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Daily Return %' =
			
			VAR _PrevClose =
			    CALCULATE(
			        MAX(fPrices[Close]),
			        DATEADD(dCalendar[Date], -1, DAY)
			    )
			RETURN
			IF(
			    NOT ISBLANK(_PrevClose),
			    DIVIDE(MAX(fPrices[Close]) - _PrevClose, _PrevClose)
			)
		lineageTag: 4e43598e-aea3-46d1-825e-00ce6fe6c17d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cumulative Return %' =
			
			VAR _FirstDate =
			    CALCULATE(
			        MIN(fPrices[Date]),
			        ALL(fPrices)
			    )
			
			VAR FirstPrice =
			    CALCULATE(
			        MAX(fPrices[Close]),
			        fPrices[Date] = _FirstDate
			    )
			
			VAR CurrentPrice =
			    MAX(fPrices[Close])
			
			RETURN
			IF(
			    NOT ISBLANK(FirstPrice),
			    DIVIDE(CurrentPrice - FirstPrice, FirstPrice)
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		lineageTag: ae7e1775-e13c-4756-b8aa-0bbc8f4aa8b8

	measure 'Rolling 30d Volatility' =
			
			STDEVX.P(
			    DATESINPERIOD(
			        dCalendar[Date],
			        MAX(dCalendar[Date]),
			        -30,
			        DAY
			    ),
			    [Daily Return %]
			)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 8b3802bb-fe9a-4c7a-8d81-9aeca5cbc332

	measure 'Running Max Price' =
			
			CALCULATE(
			    MAX(fPrices[Close]),
			    FILTER(
			        ALL(dCalendar),
			        dCalendar[Date] <= MAX(dCalendar[Date])
			    )
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0ad7ba6c-0950-41fd-b691-e15f4afebcdf

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Drawdown %' =
			
			DIVIDE(
			    MAX(fPrices[Close]) - [Running Max Price],
			    [Running Max Price]
			)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 5e4e5ea8-4ecc-4e01-8739-cbae807f92ac

	measure 'YTD Return %' =
			
			VAR StartOfYearPrice =
			    CALCULATE(
			        MAX(fPrices[Close]),
			        DATESYTD(dCalendar[Date])
			    )
			
			VAR FirstPriceYTD =
			    CALCULATE(
			        FIRSTNONBLANK(fPrices[Close], 1),
			        DATESYTD(dCalendar[Date])
			    )
			
			RETURN
			
			DIVIDE(
			    [Latest Close Price] - FirstPriceYTD,
			    FirstPriceYTD
			)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 2f2479d6-eb62-4b69-a4ff-1c37939c8343

	measure 'Current Drawdown %' =
			
			CALCULATE(
			    [Drawdown %],
			    LASTDATE(dCalendar[Date])
			)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 7ae8741a-9693-414b-b977-efe5f25ff01a

	measure 'Close Price' = SUM(fPrices[Close])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e615fd18-aa3c-40d6-8db6-06d0f263d30e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Volume = SUM(fPrices[Volume])
		formatString: #,0
		lineageTag: 3ebf9713-c8f7-4591-8c1f-20a047672287

	measure 'Rolling 30d Avg Volume' =
			
			AVERAGEX(
			    DATESINPERIOD(
			        dCalendar[Date],
			        MAX(dCalendar[Date]),
			        -30,
			        DAY
			    ),
			    CALCULATE(SUM(fPrices[Volume]))
			)
		formatString: #,0
		lineageTag: 1d42bdfe-be28-40d1-b1ba-dfe1abac13ab

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Previous Latest Close Price' =
			
			CALCULATE(
			    [Latest Close Price],
			    DATEADD(dCalendar[Date], -1, DAY)
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d0787bc4-845c-4c66-b29f-aced359940e5

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Cumulative % detail text' = "Since " & YEAR(MIN(dCalendar[Date]))
		lineageTag: 77293e81-267e-4525-a01f-2a5804bde4db

	measure 'Rolling 30d volatility detail text' = ```
			
			VAR _VOL = [Rolling 30d Volatility]
			
			VAR _LVL = 
			    SWITCH(
			        TRUE,
			        _VOL > 0.4, "High",
			        _VOL > 0.2, "Medium",
			        "Low"
			    )
			
			RETURN
			
			_LVL & " Variance"
			```
		lineageTag: 21e2a612-7ce2-40a0-a2d4-e92d5004fec9

	measure 'Max closing price' = MAX(fPrices[Close])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5bd4b5b2-8d9a-448a-9a00-8fff96247ec4

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Monthly Return %' =
			
			VAR CurrentMonthEnd =
			    EOMONTH(MAX(fPrices[Date]), 0)
			
			VAR PreviousMonthEnd =
			    EOMONTH(MAX(fPrices[Date]), -1)
			
			VAR CurrentClose =
			    CALCULATE(
			        MAX(fPrices[Close]),
			        FILTER(
			            ALL(fPrices),
			            fPrices[Date] <= CurrentMonthEnd
			                && MONTH(fPrices[Date]) = MONTH(CurrentMonthEnd)
			                && YEAR(fPrices[Date]) = YEAR(CurrentMonthEnd)
			        )
			    )
			
			VAR PreviousClose =
			    CALCULATE(
			        MAX(fPrices[Close]),
			        FILTER(
			            ALL(fPrices),
			            fPrices[Date] <= PreviousMonthEnd
			                && MONTH(fPrices[Date]) = MONTH(PreviousMonthEnd)
			                && YEAR(fPrices[Date]) = YEAR(PreviousMonthEnd)
			        )
			    )
			
			RETURN
			IF(
			    NOT ISBLANK(PreviousClose),
			    DIVIDE(CurrentClose - PreviousClose, PreviousClose)
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1c12f414-313a-4176-83db-061f874e26cf

	measure 'Annual Return %' = ```
			
			VAR _FirstDate = 
			    CALCULATE(
			        MIN(fPrices[Date]),
			        YEAR(fPrices[Date]) = SELECTEDVALUE(dCalendar[Year])
			    )
			
			VAR _FirstPriceYear =
			    CALCULATE(
			        FIRSTNONBLANK(fPrices[Close], 1),
			        fPrices[Date] = _FirstDate
			    )
			
			VAR _LastDate = 
			    CALCULATE(
			        MAX(fPrices[Date]),
			        YEAR(fPrices[Date]) = SELECTEDVALUE(dCalendar[Year])
			    )
			
			VAR _LastPriceYear =
			    CALCULATE(
			        FIRSTNONBLANK(fPrices[Close], 1),
			        fPrices[Date] = _LastDate
			    )
			
			RETURN
			IF(
			    NOT ISBLANK(_FirstPriceYear),
			    DIVIDE(_LastPriceYear - _FirstPriceYear, _FirstPriceYear)
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 64caa450-a02a-4def-b0b9-30a2ba57c206

	measure 'Rolling 12M Return %' =
			
			VAR CurrentPrice =
			    MAX(fPrices[Close])
			
			VAR Price12Mago =
			    CALCULATE(
			        MAX(fPrices[Close]),
			        DATEADD(dCalendar[Date], -12, MONTH)
			    )
			
			RETURN
			
			IF(
			    COUNTROWS(fPrices) > 0,
			    DIVIDE(CurrentPrice - Price12Mago, Price12Mago)
			)
		lineageTag: abd007c2-35bb-4448-8306-d9771463ec9c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CAGR %' =
			
			VAR _FirstDate =
			    CALCULATE(
			        MIN(fPrices[Date]),
			        ALL(fPrices)
			    )
			
			VAR _LastDate =
			    CALCULATE(
			        MAX(fPrices[Date]),
			        ALL(fPrices)
			    )
			
			VAR _FirstPrice =
			    CALCULATE(
			        MAX(fPrices[Close]),
			        fPrices[Date] = _FirstDate
			    )
			
			VAR _LastPrice =
			    CALCULATE(
			        MAX(fPrices[Close]),
			        fPrices[Date] = _LastDate
			    )
			
			VAR _Years =
			    DIVIDE(
			        DATEDIFF(_FirstDate, _LastDate, DAY),
			        365
			    )
			
			RETURN
			IF(
			    _Years > 0,
			    POWER(_LastPrice / _FirstPrice, 1 / _Years) - 1
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 39b23e04-d01d-4d7e-a62f-31efa0bff5f8

	measure 'Return Frequency' =
			
			VAR BinStart = SELECTEDVALUE('Return Bins'[Value])
			VAR BinEnd = BinStart + 0.01
			
			RETURN
			CALCULATE(
			    COUNTROWS(fPrices),
			    FILTER(
			        ADDCOLUMNS(
			            ALL(fPrices[Date]),
			            "Return", [Daily Return %]
			        ),
			        [Return] >= BinStart &&
			        [Return] < BinEnd
			    )
			)
		formatString: 0
		lineageTag: 2c159814-981f-4a92-a57e-82cc72fbd763

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

