table fPrices
	lineageTag: a98e5d81-1b3f-4da6-8fd5-ed18238bfa74

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 572c47d3-1f93-4210-8076-3c76d04fe1f5
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 7e7ff1d7-1312-4547-9948-5add5c6aa5db
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: 13797a08-1075-49d0-a415-fee2df079d6e
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 142e88cf-3f65-427b-8133-f75c3076c8dc
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: 74dfc5b7-63f7-4a15-976d-7f364736c9dd
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: 14ebdf75-b4f2-43a5-a94e-1a0c3bcb1d73
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	column Daily_Return
		dataType: double
		formatString: 0.0000000000%;-0.0000000000%;0.0000000000%
		lineageTag: 8960afa5-261a-4681-9bca-dc22c133c585
		summarizeBy: sum
		sourceColumn: Daily_Return

		annotation SummarizationSetBy = Automatic

	column Price_Range
		dataType: double
		lineageTag: f85f5a51-0daa-42e8-95c5-c582f6b8b7de
		summarizeBy: sum
		sourceColumn: Price_Range

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Change
		dataType: double
		lineageTag: b2ec5c3b-23cf-45a7-9d57-4c50172523b9
		summarizeBy: sum
		sourceColumn: Price_Change

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Daily_return_bin
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: c45bb748-102e-4075-b786-455f90d953e6
		summarizeBy: sum
		sourceColumn: Daily_return_bin

		annotation SummarizationSetBy = Automatic

	partition fPrices = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(Web.Contents(sourceUrl),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos", {{"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Daily_Return", type number}, {"Price_Range", type number}, {"Price_Change", type number}}, "en-US"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade",{{"Volume", Int64.Type}, {"Date", type date}}),
				    #"Divided Column" = Table.TransformColumns(#"Tipo Alterado", {{"Daily_Return", each _ / 100, type number}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Divided Column",{{"Daily_Return", Percentage.Type}}),
				    #"Inserted Rounding" = Table.AddColumn(#"Changed Type", "Daily_return_bin", each Number.IntegerDivide([Daily_Return], 0.05) * 0.05, Percentage.Type)
				in
				    #"Inserted Rounding"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

