table fLoan
	lineageTag: 3dc0c373-0379-46cf-a785-1ab7f2283ff2

	column applicant_id
		dataType: string
		lineageTag: 1acedc67-739e-4169-82af-f6a00beb21fa
		summarizeBy: none
		sourceColumn: applicant_id

		annotation SummarizationSetBy = Automatic

	column age
		dataType: string
		lineageTag: d623ec33-e379-4981-a641-d6f5931adad6
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 587a02e9-9fca-453f-8731-6346c2230468
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column marital_status
		dataType: string
		lineageTag: 313eee56-315f-4bdb-b03e-81e60212a386
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

	column annual_income
		dataType: string
		lineageTag: 26926f56-5ef6-4d6e-80b4-fe5dc31aca4f
		summarizeBy: none
		sourceColumn: annual_income

		annotation SummarizationSetBy = Automatic

	column loan_amount
		dataType: string
		lineageTag: ca442bdd-d7dc-4e20-af5f-e28ab25259ee
		summarizeBy: none
		sourceColumn: loan_amount

		annotation SummarizationSetBy = Automatic

	column credit_score
		dataType: string
		lineageTag: 1563ef38-11e6-488e-8724-66176dd73adf
		summarizeBy: none
		sourceColumn: credit_score

		annotation SummarizationSetBy = Automatic

	column num_dependents
		dataType: string
		lineageTag: 963310c0-0cdd-48a5-8a72-9693ae15400f
		summarizeBy: none
		sourceColumn: num_dependents

		annotation SummarizationSetBy = Automatic

	column existing_loans_count
		dataType: string
		lineageTag: 1c11c97b-cdb7-4901-8201-e3d159fe6a33
		summarizeBy: none
		sourceColumn: existing_loans_count

		annotation SummarizationSetBy = Automatic

	column employment_status
		dataType: string
		lineageTag: 87b8e235-6d53-4ae2-8aba-36c2b8b7efcb
		summarizeBy: none
		sourceColumn: employment_status

		annotation SummarizationSetBy = Automatic

	column loan_approved
		dataType: string
		lineageTag: 0406c51f-ad13-41f8-9f94-06c69850cd14
		summarizeBy: none
		sourceColumn: loan_approved

		annotation SummarizationSetBy = Automatic

	partition fLoan = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents(sourceDatasetUrl),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

